- hosts: localhost
  vars:
    ansible_python_interpreter: /Users/Hanzhen/opt/anaconda3/bin/python3
  vars_files:
    - host_vars/instance_var.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance