# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-instance1
    vol_size: 50
  - vol_name: vol-instance2
    vol_size: 100
  - vol_name: vol-instance3
    vol_size: 100
  - vol_name: vol-instance4
    vol_size: 100

# Security group
security_groups:
  - name: ssh
    description: "SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchDB
    description: "Couchdb cluster communication"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5994
    remote_ip_prefix: 0.0.0.0/0



# Instance
instances:
  - name: ins-1
    volumes: ['vol-instance1']
    flavor: uom.mse.1c4g
    nics: "net-name=qh2-uom-internal"
  - name: ins-2
    volumes: ['vol-instance2']
    flavor: uom.mse.2c9g
    nics: "net-name=qh2-uom-internal"
  - name: ins-3
    volumes: ['vol-instance3']
    flavor: uom.mse.2c9g
    nics: "net-name=qh2-uom-internal"
  - name: ins-4
    volumes: ['vol-instance4']
    flavor: uom.mse.2c9g
    nics: "net-name=qh2-uom-internal"
# "net-name=qh2-uom-internal,net-name=qh2-uom,net-name=Classic Provider"

instance_image: NeCTAR Ubuntu 18.04 LTS (Bionic) amd64 (with Docker)
instance_key: group-68-key-v2