version: "3"
services:
  couch_worker_ins4:
    image: "couchdb"
    restart: always
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=adm1n_c0uchd6
      - COUCHDB_PASSWORD=_gr0up68H1_
      - NODENAME=172.26.132.112
      - COUCHDB_COOKIE=fckcouchdb
    container_name: couch_worker_ins4